### Syntax to run: ansible-playbook -i <inventory> config.yml

# Cluster deployment playbook creates persistent volumes
- import_playbook: /usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml

# Deploy internal Docker registry
- import_playbook: /usr/share/ansible/openshift-ansible/playbooks/openshift-hosted/config.yml

# Deploy Hawkular metrics
- import_playbook: /usr/share/ansible/openshift-ansible/playbooks/openshift-metrics/config.yml

# Deploy logging
- import_playbook: /usr/share/ansible/openshift-ansible/playbooks/openshift-logging/config.yml

# Uninstall GlusterFS prior to reinstall, see KCS article: https://access.redhat.com/solutions/4098721
#- import_playbook: /usr/share/ansible/openshift-ansible/playbooks/openshift-glusterfs/uninstall.yml

# Deploy GlusterFS
- import_playbook: /usr/share/ansible/openshift-ansible/playbooks/openshift-glusterfs/config.yml

# Deploy GlusterFS for Docker registry (reference only, not used in this example)
#- import_playbook: /usr/share/ansible/openshift-ansible/playbooks/openshift-glusterfs/registry.yml
