# Install metrics
# https://access.redhat.com/documentation/en-us/openshift_container_platform/3.11/html/installing_clusters/install-config-configuring-inventory-file#advanced-install-cluster-metrics
openshift_metrics_install_metrics: true
openshift_metrics_cassandra_nodeselector: {"node-role.kubernetes.io/infra":"true"}
openshift_metrics_hawkular_nodeselector: {"node-role.kubernetes.io/infra":"true"}
openshift_metrics_heapster_nodeselector: {"node-role.kubernetes.io/infra":"true"}

# Configure NFS host group storage
# https://access.redhat.com/documentation/en-us/openshift_container_platform/3.11/html/installing_clusters/install-config-configuring-inventory-file#advanced-install-cluster-metrics-storage
openshift_metrics_cassandra_storage_type: pv
openshift_metrics_storage_kind: nfs
openshift_metrics_storage_access_modes: ['ReadWriteOnce']
openshift_metrics_storage_nfs_directory: /exports
openshift_metrics_storage_nfs_options: '*(rw,root_squash)'
openshift_metrics_storage_volume_name: metrics
openshift_metrics_storage_volume_size: 15Gi

# Optional tuning for small home labs
openshift_metrics_cassandra_limits_memory: 2G
openshift_metrics_cassandra_requests_memory: 500m
openshift_metrics_hawkular_limits_memory: 2G
openshift_metrics_hawkular_requests_memory: 500m
openshift_metrics_heapster_limits_memory: 2G
openshift_metrics_heapster_requests_memory: 500m
